### PR TITLE
Use python builtin modules instead of hand-parsing for passwd

### PR DESCRIPTION
**Pull request by rbarry82**
The `pwd` and `grp` modules are very API-stable. Use those to
parse contents instead of regular expressions

### CODE REVIEW

**Comment by rbarry82** [comment]
Hell is GitHub actions. I thought I opened this PR way earlier, but it was CI on my fork. Grabbing a huge act image to find out why GH actions behaves differently from a fresh LXD

**Comment by rbarry82** [comment]
@petevg The alternative option for cleanup.

Removes custom handling of `/etc/passwd` and `/etc/group` with filereading and regexes, and uses builtin modules.

I don't have a strong preference either way (other than a growing dislike for GH actions, and `act` doesn't seem to be a good substitute sometimes), but it keeps the UX of the library the same as apt/snap. Choice is yours for maintenance

**Review by petevg — CHANGES_REQUESTED** [review]
After reading through this and @jnsgruk's PR carefully, I think that I am in favor of his simpler approach. I am -1 to this, in favor of the simplest possible implementation of a wrapper around pwd.

(Feel free to tell me that you told me so if it turns out that the complexity would have helped us deal with a tricky edge case :-) )

**Comment by jnsgruk** [comment]
Closing for now. Thanks for this either way.

**Pull request closed without merging**
