### PR TITLE
fix: inherit environment before adding new keys

### PR DESCRIPTION
**Pull request by jsimpso**
# Current behaviour (per #60):

## Xenial
```bash
lxc launch ubuntu:xenial xenial
lxc exec xenial wget https://raw.githubusercontent.com/canonical/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec xenial python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<...>
apt.PackageError: Could not install package(s) [['python3-pymongo=3.2-1build1']]: None
```
❌

## Bionic
```bash
lxc launch ubuntu:bionic bionic
lxc exec bionic wget https://raw.githubusercontent.com/canonical/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec bionic python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<...>
apt.PackageError: Could not install package(s) [['python3-pymongo=3.6.1+dfsg1-1']]: None
```
❌

## Focal
```bash
lxc launch ubuntu:focal focal
lxc exec focal wget https://raw.githubusercontent.com/canonical/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec focal python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<apt.DebianPackage: {'_name': 'python3-pymongo', '_arch': 'amd64', '_state': <PackageState.Present: 'present'>, '_version': <apt.Version: {'_version': '3.10.1-0ubuntu2', '_epoch': ''}>}>
```
✔️

## Jammy
```bash
lxc launch ubuntu:jammy jammy
lxc exec jammy wget https://raw.githubusercontent.com/canonical/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec jammy python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<apt.DebianPackage: {'_name': 'python3-pymongo', '_arch': 'amd64', '_state': <PackageState.Present: 'present'>, '_version': <apt.Version: {'_version': '3.11.0-1build4', '_epoch': ''}>}>
```
✔️
# Post-change behaviour

## Xenial
```bash
lxc exec xenial -- rm apt.py
lxc exec xenial wget https://raw.githubusercontent.com/jsimpso/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec xenial python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<apt.DebianPackage: {'_arch': 'amd64', '_state': <PackageState.Present: 'present'>, '_name': 'python3-pymongo', '_version': <apt.Version: {'_version': '3.2-1build1', '_epoch': ''}>}>
```
✔️

## Bionic
```bash
lxc exec bionic -- rm apt.py
lxc exec bionic wget https://raw.githubusercontent.com/jsimpso/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec bionic python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<apt.DebianPackage: {'_name': 'python3-pymongo', '_arch': 'amd64', '_state': <PackageState.Present: 'present'>, '_version': <apt.Version: {'_version': '3.6.1+dfsg1-1', '_epoch': ''}>}>
```
✔️

## Focal
```bash
lxc exec focal -- rm apt.py
lxc exec focal wget https://raw.githubusercontent.com/jsimpso/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec focal -- apt remove python3-pymongo -y
lxc exec focal python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<apt.DebianPackage: {'_name': 'python3-pymongo', '_arch': 'amd64', '_state': <PackageState.Present: 'present'>, '_version': <apt.Version: {'_version': '3.10.1-0ubuntu2', '_epoch': ''}>}>
```
✔️

## Jammy
```bash
lxc exec jammy -- rm apt.py
lxc exec jammy wget https://raw.githubusercontent.com/jsimpso/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec jammy -- apt remove python3-pymongo -y
lxc exec jammy python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<apt.DebianPackage: {'_name': 'python3-pymongo', '_arch': 'amd64', '_state': <PackageState.Present: 'present'>, '_version': <apt.Version: {'_version': '3.11.0-1build4', '_epoch': ''}>}>
```
✔️

### CODE REVIEW

**Review by jnsgruk — CHANGES_REQUESTED** [review]
Chang LGTM, looks like there needs to be some adjustment to the test suite, though. Could you also bump the `LIBPATCH` number? :)

**Comment by benhoyt** [comment]
@jsimpso Yep, the tests need to be fixed. Could you also update the lib's patch version at the top of the file?

**Comment by jsimpso** [comment]
Sorry for the delayed response. I've updated the patch number and fixed up the unit tests as requested.

I can see that tests are still failing to run at the moment, but unless I'm mistaken that issue looks unrelated to the code being changed. Unit and integration tests are passing when run locally, for what it's worth.

Please let me know if you want me to make any further changes or look more closely at those failures!

**Comment by benhoyt** [comment]
Excellent, thanks. I'll fix up the unit tests (latest ops, which is 2.0.0+, we're explicitly fetching latest `main`) only works on Python 3.8+ now, so I'll remove those older Python versions from CI and add newer ones. Not sure what the deal is with integration tests, may be the same issue, but I'll look into it.

**Comment by jnsgruk** [comment]
The integration test failure is due to flappy test that relies on logs - I've seen this before, we probably need to think a bit harder about that test, but it shouldn't block this PR :)

**Comment by benhoyt** [comment]
@jsimpso Can you please allow me to push to your branch/fork? I've got a couple of commits to add to fix the tests. Alternatively apply these two patches yourself:

* [0001-Only-run-CI-on-Python-3.8-and-3.10-like-ops.patch.txt](https://github.com/canonical/operator-libs-linux/files/10454858/0001-Only-run-CI-on-Python-3.8-and-3.10-like-ops.patch.txt)
* [0002-Fix-test-that-breaks-when-local-timezone-is-not-UTC.patch.txt](https://github.com/canonical/operator-libs-linux/files/10454859/0002-Fix-test-that-breaks-when-local-timezone-is-not-UTC.patch.txt)

**Review by benhoyt — APPROVED** [review]

**Comment by benhoyt** [comment]
@jnsgruk Could you please update your review? I've opened a separate issue on the integration tests logging issue (not related to this PR): https://github.com/canonical/operator-libs-linux/issues/65

**Review by jnsgruk — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
